// presentations/13-observer-pattern-demos/demo-4-react/src/CurrentConditions.tsx
import { useEffect } from 'react';
import { useWeather } from './WeatherContext';

export function CurrentConditions() {
  const { weather, registerSubscriber, unregisterSubscriber } = useWeather();

  // Mount = subscribe, unmount = unsubscribe
  useEffect(() => {
    registerSubscriber('CurrentConditionsDisplay');
    return () => unregisterSubscriber('CurrentConditionsDisplay');
  }, [registerSubscriber, unregisterSubscriber]);

  return (
    <article>
      <header>Current Conditions</header>
      <p>
        <strong>{weather.temperature}°F</strong> | {weather.humidity}% humidity |{' '}
        {weather.pressure} hPa
      </p>
    </article>
  );
}

// presentations/13-observer-pattern-demos/demo-3-angular/src/app/current-conditions.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { WeatherService, WeatherData } from './weather.service';

@Component({
  selector: 'app-current-conditions',
  templateUrl: './current-conditions.component.html',
})
export class CurrentConditionsComponent implements OnInit, OnDestroy {
  data: WeatherData = { temperature: 0, humidity: 0, pressure: 0 };
  private subscription!: Subscription;

  constructor(private weatherService: WeatherService) {}

  // subscribe() = register as observer
  ngOnInit(): void {
    this.subscription = this.weatherService.weather$.subscribe(
      (weather) => (this.data = weather)
    );
    this.weatherService.registerSubscriber('CurrentConditionsDisplay');
  }

  // unsubscribe() = prevent lapsed listener leak
  ngOnDestroy(): void {
    this.subscription.unsubscribe();
    this.weatherService.unregisterSubscriber('CurrentConditionsDisplay');
  }
}

<article>
  <header>Current Conditions</header>
  <p>
    <strong>{{ data.temperature }}°F</strong> |
    {{ data.humidity }}% humidity |
    {{ data.pressure }} hPa
  </p>
</article>
