// presentations/13-observer-pattern-demos/demo-3-angular/src/app/fire.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { WeatherService } from './weather.service';

@Component({
  selector: 'app-fire',
  templateUrl: './fire.component.html',
  styleUrl: './fire.component.css',
})
export class FireComponent implements OnInit, OnDestroy {
  burning = false;
  flames: { id: number; x: number; speed: number; delay: number; size: number; opacity: number; waggle: number }[] = [];
  private subscription!: Subscription;

  constructor(private weatherService: WeatherService) {
    this.flames = Array.from({ length: 50 }, (_, i) => ({
      id: i,
      x: Math.random() * 100,
      speed: 2 + Math.random() * 4,
      delay: Math.random() * 4,
      size: 28 + Math.random() * 160,
      opacity: 0.5 + Math.random() * 0.5,
      waggle: 1.5 + Math.random() * 2,
    }));
  }

  ngOnInit(): void {
    this.subscription = this.weatherService.weather$.subscribe((weather) => {
      const hasData = weather.temperature !== 0 || weather.humidity !== 0 || weather.pressure !== 0;
      this.burning = hasData && weather.temperature >= 110;
    });
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
}

@if (burning) {
  <div class="fire-container" aria-hidden="true">
    @for (flame of flames; track flame.id) {
      <div
        class="flame"
        [style.left.%]="flame.x"
        [style.animation-duration]="flame.speed + 's, ' + flame.waggle + 's'"
        [style.animation-delay.s]="flame.delay"
        [style.font-size.px]="flame.size"
        [style.opacity]="flame.opacity"
      >&#128293;</div>
    }
  </div>
}

// presentations/13-observer-pattern-demos/demo-4-react/src/Fire.tsx
import { useMemo } from 'react';
import { useWeather } from './WeatherContext';
import './Fire.css';

export function Fire() {
  const { weather, hasData } = useWeather();
  const burning = hasData && weather.temperature >= 110;

  const flames = useMemo(
    () =>
      Array.from({ length: 50 }, (_, i) => ({
        id: i,
        x: Math.random() * 100,
        speed: 2 + Math.random() * 4,
        delay: Math.random() * 4,
        size: 28 + Math.random() * 160,
        opacity: 0.5 + Math.random() * 0.5,
        waggle: 1.5 + Math.random() * 2,
      })),
    []
  );

  if (!burning) return null;

  return (
    <div className="fire-container" aria-hidden="true">
      {flames.map((f) => (
        <div
          key={f.id}
          className="flame"
          style={{
            left: `${f.x}%`,
            animationDuration: `${f.speed}s, ${f.waggle}s`,
            animationDelay: `${f.delay}s`,
            fontSize: `${f.size}px`,
            opacity: f.opacity,
          }}
        >
          &#128293;
        </div>
      ))}
    </div>
  );
}
