// presentations/13-observer-pattern-demos/demo-3-angular/src/app/snow.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { WeatherService } from './weather.service';

@Component({
  selector: 'app-snow',
  templateUrl: './snow.component.html',
  styleUrl: './snow.component.css',
})
export class SnowComponent implements OnInit, OnDestroy {
  snowing = false;
  flakes: { id: number; x: number; speed: number; delay: number; size: number; opacity: number }[] = [];
  private subscription!: Subscription;

  constructor(private weatherService: WeatherService) {
    // Pre-generate snowflakes with random properties
    this.flakes = Array.from({ length: 60 }, (_, i) => ({
      id: i,
      x: Math.random() * 100,
      speed: 3 + Math.random() * 5,
      delay: Math.random() * 5,
      size: 28 + Math.random() * 120,
      opacity: 0.4 + Math.random() * 0.6,
    }));
  }

  ngOnInit(): void {
    this.subscription = this.weatherService.weather$.subscribe((weather) => {
      const hasData = weather.temperature !== 0 || weather.humidity !== 0 || weather.pressure !== 0;
      this.snowing = hasData && weather.temperature <= 32;
    });
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
}

@if (snowing) {
  <div class="snow-container" aria-hidden="true">
    @for (flake of flakes; track flake.id) {
      <div
        class="snowflake"
        [style.left.%]="flake.x"
        [style.animation-duration.s]="flake.speed"
        [style.animation-delay.s]="flake.delay"
        [style.font-size.px]="flake.size"
        [style.opacity]="flake.opacity"
      >&#10052;</div>
    }
  </div>
}

// presentations/13-observer-pattern-demos/demo-4-react/src/Snow.tsx
import { useMemo } from 'react';
import { useWeather } from './WeatherContext';
import './Snow.css';

export function Snow() {
  const { weather, hasData } = useWeather();
  const snowing = hasData && weather.temperature <= 32;

  const flakes = useMemo(
    () =>
      Array.from({ length: 60 }, (_, i) => ({
        id: i,
        x: Math.random() * 100,
        speed: 3 + Math.random() * 5,
        delay: Math.random() * 5,
        size: 28 + Math.random() * 120,
        opacity: 0.4 + Math.random() * 0.6,
      })),
    []
  );

  if (!snowing) return null;

  return (
    <div className="snow-container" aria-hidden="true">
      {flakes.map((f) => (
        <div
          key={f.id}
          className="snowflake"
          style={{
            left: `${f.x}%`,
            animationDuration: `${f.speed}s`,
            animationDelay: `${f.delay}s`,
            fontSize: `${f.size}px`,
            opacity: f.opacity,
          }}
        >
          &#10052;
        </div>
      ))}
    </div>
  );
}
