// presentations/13-observer-pattern-demos/demo-3-angular/src/app/statistics.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { Subscription } from 'rxjs';
import { WeatherService } from './weather.service';

@Component({
  selector: 'app-statistics',
  imports: [DecimalPipe],
  templateUrl: './statistics.component.html',
})
export class StatisticsComponent implements OnInit, OnDestroy {
  avg = 0;
  min = Infinity;
  max = -Infinity;
  readings: number[] = [];
  private subscription!: Subscription;

  constructor(private weatherService: WeatherService) {}

  ngOnInit(): void {
    this.subscription = this.weatherService.weather$.subscribe((weather) => {
      if (weather.temperature === 0 && weather.humidity === 0) return;
      this.readings.push(weather.temperature);
      this.avg =
        this.readings.reduce((a, b) => a + b, 0) / this.readings.length;
      this.min = Math.min(...this.readings);
      this.max = Math.max(...this.readings);
    });
    this.weatherService.registerSubscriber('StatisticsDisplay');
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
    this.weatherService.unregisterSubscriber('StatisticsDisplay');
  }
}

<article>
  <header>Statistics</header>
  <p>
    Avg: <strong>{{ avg | number:'1.1-1' }}°F</strong> |
    Min: {{ min }}°F |
    Max: {{ max }}°F
  </p>
  <small>{{ readings.length }} reading(s) recorded</small>
</article>

// presentations/13-observer-pattern-demos/demo-4-react/src/Statistics.tsx
import { useEffect, useRef } from 'react';
import { useWeather } from './WeatherContext';

export function Statistics() {
  const { weather, hasData, registerSubscriber, unregisterSubscriber } = useWeather();
  const readings = useRef<number[]>([]);
  const lastTemp = useRef<number | null>(null);

  // Track readings — only push when temperature actually changes
  if (hasData && weather.temperature !== lastTemp.current) {
    lastTemp.current = weather.temperature;
    readings.current.push(weather.temperature);
  }

  const count = readings.current.length;
  const avg = count > 0 ? readings.current.reduce((a, b) => a + b, 0) / count : 0;
  const min = count > 0 ? Math.min(...readings.current) : 0;
  const max = count > 0 ? Math.max(...readings.current) : 0;

  useEffect(() => {
    registerSubscriber('StatisticsDisplay');
    return () => unregisterSubscriber('StatisticsDisplay');
  }, [registerSubscriber, unregisterSubscriber]);

  return (
    <article>
      <header>Statistics</header>
      <p>
        Avg: <strong>{avg.toFixed(1)}°F</strong> | Min: {min}°F | Max: {max}°F
      </p>
      <small>{count} reading(s) recorded</small>
    </article>
  );
}
